default:
  tags:
    - kxi-gitlab-runner


stages:
  - build


docker-build-push:
  stage: build
  image: "docker:20.10.23"
  before_script:
    - |
      if [ -z "$DOCKER_AUTH_CONFIG" ]
      then
        echo "\$DOCKER_AUTH_CONFIG not set, unable to authenticate against container registries"
        exit 1
      fi

    - mkdir -p $HOME/.docker && echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
    - echo ${INT_NEXUS_PASS_RW} | docker login ${INSIGHTS_DEV_NEXUS_REGISTRY} -u ${INT_NEXUS_USER_RW} --password-stdin
  script:
    - IMAGE_URL="$INSIGHTS_DEV_NEXUS_REGISTRY/benchmarking/nano:$(yq -r '.pub' version.yaml)"
    - docker build --pull -t "${IMAGE_URL}" .
    - docker push "${IMAGE_URL}"
  after_script:
    - docker rmi "${IMAGE_URL}"

  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
