default:
  tags:
    - kxi-gitlab-runner

stages:
  - build
  - test

.docker-beforescript:
  stage: build
  image: "docker:20.10.23"
  before_script:
    - |
      if [ -z "$DOCKER_AUTH_CONFIG" ]
      then
        echo "\$DOCKER_AUTH_CONFIG not set, unable to authenticate against container registries"
        exit 1
      fi

    - mkdir -p $HOME/.docker && echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
    - echo ${INT_NEXUS_PASS_RW} | docker login ${INSIGHTS_DEV_NEXUS_REGISTRY} -u ${INT_NEXUS_USER_RW} --password-stdin
  script:
    - INSIGHTSVER=4.1.6
    - wget https://${INT_NEXUS_USER_RO}:${INT_NEXUS_PASS_RO}@ext-nexus.kxi-dev.kx.com/repository/kx-insights-packages/kdbInsightsCore/${INSIGHTSVER}-rc1/kdb-insights-core.tar
    - docker load < kdb-insights-core.tar
    - IMAGE_URL="$INSIGHTS_DEV_NEXUS_REGISTRY/benchmarking/nano:$(cat version.txt)"
    - docker build -t "${IMAGE_URL}" .
    - docker push "${IMAGE_URL}"
    - docker rmi "${IMAGE_URL}"
    - docker rmi kdb-insights-core:${INSIGHTSVER}
    - echo "IMAGE_URL=${IMAGE_URL}" > img.env

docker-buildpub-push:
  variables:
    TARGET: "pub"
  extends:
    - .docker-beforescript
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

docker-builddev-push:
  variables:
    TARGET: "dev"
  extends:
    - .docker-beforescript
  artifacts:
    reports:
      dotenv: img.env
  rules:
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'

.nano:
  stage: test
  image:
    name: "${IMAGE_URL}"
    entrypoint: [""]
    pull_policy: always
  needs:
    - job: docker-builddev-push
  variables:
    QLIC: /tmp/qlic
  before_script:
    - mkdir -p "$QLIC"
    - echo -n "$KDB_LICENSE_B64" | base64 -d > "$QLIC/kc.lic"
    - source ./config/env
  rules:
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
      changes:
        - "!README.md"
        - "!LICENSE"
      when: on_success
    - when: never
  artifacts:
    paths:
      - logs/*/*.log
    expire_in: 1 day
    when: on_failure

nano-single:
  extends:
    - .nano
  script:
    - echo "${APPDIR}/data" > ./partitions
    - DBSIZE=TINY SUDO="" ./nano.sh

nano-multi:
  extends:
    - .nano
  script:
    - echo "${APPDIR}/data0" > ./partitions
    - echo "${APPDIR}/data1" >> ./partitions
    - DBSIZE=TINY SUDO="" ./nano.sh -p 3

nano-multi-cpuonly:
  extends:
    - .nano
  script:
    - echo "${APPDIR}/data0" > ./partitions
    - echo "${APPDIR}/data1" >> ./partitions
    - DBSIZE=TINY SUDO="" ./nano.sh -p 3 -s cpuonly

multiproc-multi:
  extends:
    - .nano
  script:
    - echo "${APPDIR}/data0" > ./partitions
    - echo "${APPDIR}/data1" >> ./partitions
    - DBSIZE=TINY SUDO="" ./multiproc.sh -l 3